version: "3"
services:
  web-nzshop:
    image: topstory/nzshop-web:1.0
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - /data/nzshop.cn:/usr/share/nginx/html
    container_name: nzshop-container
  web-crm:
    build:
      context: /data/MicaCRM
      dockerfile: Dockerfile
    hostname: crm.nzshop.cn
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    container_name: web-crm-container
    env_file:
      - .env
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /data/DB_Backup:/backup
    container_name: mariadb-container
volumes:
  db_data:
