version: "3"
services:
  web-crm:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
  db:
    image: mariadb:11.2.2
    environment:
      MYSQL_ROOT_PASSWORD: nz21usana
      MYSQL_DATABASE: fpcrm
      MYSQL_USER: fpcrmuser
      MYSQL_PASSWORD: lc100purenz
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
