version: "3"
services:
  web-nzshop:
    image: topstory/nzshop-web:1.0
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - /data/nzshop.cn:/usr/share/nginx/html
    container_name: nzshop-container
  web-crm:
    build:
      context: /data/MicaCRM
      dockerfile: Dockerfile
    hostname: crm.nzshop.cn
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    container_name: web-crm-container
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: nz21usana
      MYSQL_DATABASE: fpcrm
      MYSQL_USER: fpcrmuser
      MYSQL_PASSWORD: lc100purenz
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /data/DB_Backup:/backup
    container_name: mysql-container
volumes:
  db_data:
